app_package/main/routes.py
from flask import Blueprint

from flask import render_template, url_for, redirect, flash, request, \
     current_app, send_from_directory
from app_package import db, bcrypt, mail
from app_package.models import Users
import sqlalchemy as sa
# from app_package.users.forms import LoginForm, RegistrationForm, \
#     ResetPasswordForm, AccessNewForm, AccessEditForm, RequestResetForm
from flask_login import login_required
import os
import shutil #copy file library
from app_package.main.utils import get_size_dict

main = Blueprint('main', __name__)


# @main.route("/upload_page", methods=["GET","POST"])
# @login_required
# def upload_page():

#     isExist = os.path.exists(current_app.config['UPLOAD_DIR'])
#     if not isExist:
#         os.makedirs(current_app.config['UPLOAD_DIR'])

#     upload_data_file_list = os.listdir(current_app.config['UPLOAD_DIR'])

#     size_list=[]
#     for i in upload_data_file_list:
#         size=os.path.getsize(os.path.join(current_app.config['UPLOAD_DIR'],i))
#         print('size::::', size)
#         if len(str(size))>9:
#             size= str(f"{round(size/10**9,1):,}") +' GB'
#         elif len(str(size))>3:
#             size= str(f"{round(size/10**6,2):,}") +' MB'
#         else:
#             size=str(f"{size:,}")+' bytes'
#         size_list.append(size)
    
#     files_info_lists=zip(upload_data_file_list,size_list)


#     if request.method == 'POST':

#         filesDict = request.files.to_dict()
#         formDict = request.form.to_dict()
        
#         # print('formDict:::',formDict)

#         # if request.files['media']:
#         if formDict.get('file_to_delete'):
#             os.remove(os.path.join(current_app.config['UPLOAD_DIR'],formDict.get('file_to_delete')))
#             return redirect(url_for('main.upload_page', files_info_lists=files_info_lists))
#         elif filesDict.get('upload_file'):
#             print('filesDict:::',filesDict)
#             uploadData=request.files['upload_file']
#             uploadData.save(os.path.join(current_app.config['UPLOAD_DIR'], uploadData.filename))
#             return redirect(url_for('main.upload_page', files_info_lists=files_info_lists))
#     return render_template('upload_page.html', files_info_lists=files_info_lists)

    
    
@main.route("/download_data_page", methods=["GET","POST"])
@login_required
def download_data_page():
    file_name=request.args.get('file_name')

    return send_from_directory(os.path.join(
        current_app.config['UPLOAD_DIR']),file_name, as_attachment=True)


@main.route("/upload", methods=["GET","POST"])
@login_required
def upload_page():

    #"Uploaded" files - server files like in the real thing
    isExist = os.path.exists(current_app.config['UPLOAD_DIR'])
    if not isExist:
        os.makedirs(current_app.config['UPLOAD_DIR'])

    upload_file_name_list = os.listdir(current_app.config['UPLOAD_DIR'])
    upload_file_dict=get_size_dict(upload_file_name_list)
    # uploaded_files_info_lists=zip(upload_data_file_list,size_list)

    #"Local" files - servers side files that are built to look like local client machine
    isExist = os.path.exists(current_app.config['TEST_DIR'])
    if not isExist:
        os.makedirs(current_app.config['TEST_DIR'])
        for i in range(0,2):
            with open(os.path.join(current_app.config['TEST_DIR'],f'test_0{i}.txt'), 'w') as newfile:
                newfile.write(f'Test file {i}')
                newfile.close


    local_dir_files=os.listdir(current_app.config['TEST_DIR'])
    # local_dir_files.remove('sub_directory')
    local_files_info_dict={i:[os.path.join(current_app.config['TEST_DIR'],i),False] for i in local_dir_files}
    print('local_dir_files::',local_dir_files)

    selected_files=''
    if request.args.get('selected_files'):
        request_items = request.args.to_dict(flat=False)
        selected_files = request_items.get('selected_files')
        for i in selected_files:
            local_files_info_dict[i] = [local_files_info_dict[i][0],True]


    if request.method == 'POST':
        formDict = request.form.to_dict()
        print('formDict:::', formDict)
        
        #select file for upload from "local" directory --In Modal
        if formDict.get('select_file')=='True':
            selected_files = [i[5:] for i,j in formDict.items() if i[:5]=='file_']
            return redirect(url_for('main.upload_page', selected_files=selected_files))
        
        #upload selected_files
        elif formDict.get('upload') == 'True':
            for i in selected_files:
                source= local_files_info_dict[i][0]
                destination=os.path.join(current_app.config['UPLOAD_DIR'],i)
                shutil.copyfile(source, destination)
            return redirect(url_for('main.upload_page'))

        #delete uploaded file
        elif formDict.get('file_to_delete'):
            os.remove(os.path.join(current_app.config['UPLOAD_DIR'],formDict.get('file_to_delete')))
            return redirect(url_for('main.upload_page', local_files_info_dict=local_files_info_dict))

    return render_template('upload_page_mock.html', selected_files=selected_files,
        local_files_info_dict=local_files_info_dict, upload_file_dict=upload_file_dict, len=len)

app_package/users/routes.py
from flask import Blueprint
from flask import render_template, url_for, redirect, flash, request, \
     current_app, send_from_directory, abort
from app_package import db, bcrypt, mail
from app_package.models import Users
import sqlalchemy as sa
from app_package.users.forms import LoginForm, RegistrationForm, \
    ResetPasswordForm, AccessNewForm, AccessEditForm, RequestResetForm
from flask_login import login_user, current_user, logout_user, login_required
import os
from flask_mail import Message
import json
from app_package.users.utils import build_db, remove_non_admin, \
    add_admin_users

users = Blueprint('users', __name__)


@users.route("/", methods=["GET","POST"])
@users.route("/home", methods=["GET","POST"])
def home():

    #Handle access and database
    if current_user.is_authenticated:
        print('HOME SCReen::', current_user.email)
        return redirect(url_for('main.upload_page'))
    elif 'users' in sa.inspect(db.engine).get_table_names():
        print('db already exists')
    else:
        build_db()#and add admin users
        

    form = LoginForm()

    if request.args.get('email_entry'):
        form.email.data=request.args.get('email_entry')
        form.password.data=request.args.get('pass_entry')

    if form.validate_on_submit():
        #remove anyone not current user or in admin.json
        remove_non_admin()
        print('All Users:::', Users.query.all())

        # if not in db, add admin.json user missing
        add_admin_users()
        
        user = Users.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)

            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.upload_page'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('home.html', form=form)

@users.route("/register", methods=["GET","POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.upload_page'))
    form = RegistrationForm()
    if form.validate_on_submit():

        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = Users(email=form.email.data, password=hashed_password, permission='1')
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.email.data}!', 'success')
        return redirect(url_for('users.home'))
    return render_template('register.html', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('users.home'))


@users.route("/password_change", methods=["GET","POST"])
@login_required
def password_change():
    form = ResetPasswordForm()
    if form.validate_on_submit():
        formDict = request.form.to_dict()
        if formDict.get('no_change') != 'guest_email':
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            current_user.password = hashed_password
            db.session.commit()
            flash('Your password has been updated!', 'success')
        else:
            flash('This user cannot change passwords.', 'warning')
    return render_template('password.html', form=form)



def send_new_user_email(user):
    # token = user.get_reset_token()
    msg = Message('Access DD File Share',
                  sender=current_app.config['MAIL_USERNAME'],
                  recipients=[user.email])
    msg.body = f'''Visit the following link:
{url_for('users.home', _external=True)}

Login with your email address and the current password is your email address before the @
'''
    mail.send(msg)



@users.route("/access", methods=["GET","POST"])
@login_required
def access():

    all_users=[(i.id,i.email,i.permission) for i in Users.query.all()]

    form=AccessNewForm()

    if form.submit.data and form.validate_on_submit():
        # formDict = request.args.to_dict()
        formDict = request.form.to_dict()
        new_email=form.email.data
        hashed_password = bcrypt.generate_password_hash(new_email[:new_email.find('@')]).decode('utf-8')
        
        user=Users(email=new_email, password=hashed_password, permission=form.add_privilege.data)
        db.session.add(user)
        db.session.commit()
        
        #TODO: Send email to new user with password
        if form.send_email.data:
            send_new_user_email(user)
            flash(f'{new_email} has been granted access!', 'success')
        else:
            flash(f'{new_email} has access!', 'success')
        return redirect(url_for('main.upload_page'))

    return render_template('access.html', form=form, all_users=all_users, len=len)



@users.route("/edit_access", methods=["GET","POST"])
@login_required
def access_edit():
    all_users=[(i.id,i.email,i.permission) for i in Users.query.all()]
    print('all_users::',all_users)
    if current_user.email =='guest@DashAndData.com':
        all_users.remove((1,'guest@DashAndData.com','1'))
    else:
        all_users.remove((1,'guest@DashAndData.com','1'))
        for i in all_users:
            if i[1]==current_user.email:
                all_users.remove(i)


    if request.method == 'POST':
        formDict = request.form.to_dict()
        if formDict.get('update_button') == 'True':

            for i in all_users:

                if i[2] == '1' and not formDict.get(f'add_privilege_for {i[0]}'):

                    Users.query.get(i[0]).permission = 0
                    db.session.commit()
                    flash(f'{i[1]} has had privileges removed', 'warning')
                if i[2] == '0' and formDict.get(f'add_privilege_for {i[0]}'):
                    Users.query.get(i[0]).permission = 1
                    db.session.commit()
                    flash(f'{i[1]} has been granted add privileges!', 'success')
        elif formDict.get('delete_button')=='':
            db.session.query(Users).filter(Users.email==formDict.get('delete_record_email')).delete()
            db.session.commit()
        return redirect(url_for('users.access_edit'))
    return render_template('access_edit.html', all_users=all_users, len=len)


def send_reset_email(user):
    token = user.get_reset_token()
    msg = Message('Password Reset Request',
                  sender=current_app.config['MAIL_USERNAME'],
                  recipients=[user.email])
    msg.body = f'''To reset your password, visit the following link:
{url_for('users.reset_token', token=token, _external=True)}

If you did not make this request then simply ignore this email and no changes will be made.
'''
    mail.send(msg)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.upload_page'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password (check main and spam folders).', 'success')
        return redirect(url_for('users.home'))
    return render_template('reset_request.html', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.upload_page'))
    user = Users.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.home'))
    return render_template('password.html', title='Reset Password', form=form)

app_package/templates/access.html
{% extends "layout.html" %}
{% block title %} Add User {% endblock %}
{% block main %}
<section class="Access">

        <div class="form_section_login">

            <h1>Add User</h1>

            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.email.label() }}
                </div>
                <div class="form-group">
                    {% if form.email.errors %}
                    {{ form.email(class="form-control wider_input_login") }}
                    <div class="">
                        {% for error in form.email.errors %}
                        <span class="text-warning">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-control wider_input_login") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.add_privilege(checked=True, class="" ) }}
                    {{ form.add_privilege.label(class="") }}
                </div>
                <div class="form-group">
                    {{ form.send_email(checked=True, class="" ) }}
                    {{ form.send_email.label(class="") }}
                </div>
                    <br/>
                    <div class="button_group">
                        <div class="">
                            {{ form.submit(class="btn btn-primary") }}
                        </div>


                    </div>
            </form>
        </div>

    <hr/>

</div>


</section>


{% endblock %}

app_package/templates/error.html
{% extends "layout.html" %}
{% block title %} {{ error_number }} {% endblock %}
{% block main %}
<section class="Error">
    <div class="error_body">
       <h1>Ooops... {{ error_number }}</h1>
       <h3 >{{ error_message }}</h3>
    </div>
</section>

{% endblock %}

app_package/templates/home.html
{% extends "layout.html" %}
{% block title %} File Share Home {% endblock %}
{% block main %}
<section class="Home">

    {% if not current_user.is_authenticated %}
        
        <!-- If NOT logged in show -->
        <div class="form_section_login">

            <h1>Login</h1>

            <form method="POST" action="">
                {{ form.csrf_token }}
                <div class="form-group">
                    {{ form.email.label() }}
                </div>
                <div class="form-group">
                    {% if form.email.errors %}
                    {{ form.email(class="form-control wider_input_login") }}
                    <div class="">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-control wider_input_login") }}
                    {% endif %}
                </div>


                <div class="form-group">
                    {{ form.password.label() }}
                </div>
                <div class="form-group">
                    {% if form.password.errors %}
                    {{ form.password(class="form-control wider_input_login") }}
                    <div class="invalid_feedback">
                        {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.password(class="form-control wider_input_login") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.show_password(class="", id="show_password") }}
                    {{ form.show_password.label(class="") }}
                </div>


                    <div class="button_group">
                        <div class="form-submit">
                            {{ form.submit(class="btn btn-primary") }}
                            <a class="btn btn-info" href="{{ url_for('users.home', email_entry='guest@DashAndData.com', pass_entry='test' ) }}">Login as guest
                                </a>
                        </div>

                        <small class="text-muted ml-2">
                            <a href="{{ url_for('users.reset_request') }}">forgot password?</a>
                        </small>

                    </div>


            </form>
        </div>


        {% else %}
                <!-- If Logged in show Logout -->
                <h1>you're logged in</h1>
        {% endif %}

        
        

</section>
<script>
    window.addEventListener("load", function(){
        var checkbox  = document.getElementById('show_password');
        var x = document.getElementById('{{form.password.id}}');
        checkbox.addEventListener('change', function() {
            if(this.checked) {
                x.type = 'text'; 
            } else {
                x.type = 'password'; 
            }
        });
    });
</script>

{% endblock %}

app_package/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Import our custom stylesheet -->
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/main.css') }}">

    <!-- Needed for Dropdown -->
    <script src="../static/node_modules/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <!-- Ohter files needed for modals and tables-->
    <script src="../static/otherBootstrapFiles/jquery-3.5.1.js"></script>
    <link rel="stylesheet" type="text/css" href="../static/otherBootstrapFiles/jquery.dataTables.min.css">
    <script type = "text/javascript" src="../static/otherBootstrapFiles/jquery.dataTables.min.js"></script>

    
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <section class="navbar_section">
        <div class="navbar navbar-expand-lg navbar-dark bg-primary navbar_custom">

            <div class="nav_left">
                <a href="https://dashanddata.com" >
                    <div class="logo">
                        <img class="dandd_logo" src="../static/images/dashAndDataLogo02_light.png">
                    </div>
                
                </a>
            </div>
    
            <div class="nav_middle">
                
                {% if current_user.is_authenticated %}
                    {% if current_user.email.rfind('@') %}
                        <h2 class="small_screen">{{ current_user.email[:current_user.email.rfind('@') ] }}</h2>
                        <h2 class="big_screen">{{ current_user.email }}</h2>
                    {% endif %}
    
                {% endif %}
            </div>


            <img class="mobile-menu" id="mobile-cta" src="../static/images/menu.svg" alt="Open Navigation">

            

            <nav>
                    <img id="mobile-exit" class="mobile-menu-exit" src="../static/images/exit.svg" alt="Close Navigation">
                    <ul>
                        {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('main.upload_page') }}">Upload</a></li>
                        <li class="nav-item dropdown">
                            <a href="#" class="dropdown-toggle" id="navbarDropdown2" role="button"
                                data-bs-toggle="dropdown"aria-expanded="false">Admin</a>
    
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                                <a class="dropdown-item" href="{{ url_for('users.password_change') }}">Password</a>
                                {% if current_user.permission == '1' %}
                                <a class="dropdown-item" href="{{ url_for('users.access') }}">Add Access</a>
                                <a class="dropdown-item" href="{{ url_for('users.access_edit') }}">Edit Access</a>
                                {% endif %}
                            </div>
                        </li>
                        <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
                        {% else %}
                        <li><a href="{{ url_for('users.home') }}">Login</a></li>
                        <li><a href="{{ url_for('users.register') }}">Register</a></li>
                        {% endif %}
                        <li><a href="https://dashanddata.com/blog/blog01">Docs</a></li>
                    </ul>
            </nav>
    

        </div>
    </section>

      <main role="main" class="container">
          <div class="row">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          
          </div>
      </main>
      



    {% block main %}{% endblock %}

    <script>
        const mobileBtn = document.getElementById('mobile-cta')
            nav = document.querySelector('nav')
            mobileBtnExit = document.getElementById('mobile-exit');

        mobileBtn.addEventListener('click', () => {
            nav.classList.add('menu-btn');
        })

        mobileBtnExit.addEventListener('click', () => {
            nav.classList.remove('menu-btn');
        })
    </script>

</body>
</html>

app_package/templates/reset_request.html
{% extends "layout.html" %}
{% block title %}Request Reset {% endblock %}
{% block main %}
<section class="ResetRequest">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <!-- <div class="form_section_login"> -->
        <div class="form_section_login">
            <legend class="border-bottom mb-4">Reset Password</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid wider_input_login") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg wider_input_login") }}
                {% endif %}
            </div>
        
            <div class="button_custom">
                {{ form.submit(class="btn btn-info ") }}
            </div>
        </div>
    </form>
</section>
{% endblock %}

app_package/templates/upload_page.html
{% extends "layout.html" %}
{% block title %} Upload Page {% endblock %}
{% block main %}

<section class="UploadPage">
    <div class="UploadDiv">
        <h1>Upload</h1>
            <div class="UploadDivSub">
                <form method=POST enctype=multipart/form-data action="{{ url_for('main.upload_page') }}">
                    <input type=file id="media" name="upload_file" class="btn btn-secondary">
                    <button onclick="update()" class="btn btn-primary" ><i class="fa fa-trash"></i> Upload</button>
                </form>

                <div class="float_containter1">

                    <div class="child">
                        <h5>Upload Status:</h5>
                    </div> 

                    <div class="child progress" id="Progress_Status">
                        <div class="progress-bar progress-bar-striped bg-info" id="myprogressBar" role="progressbar"></div>
                    </div>

                </div>

            </div>
    </div>
    <hr/>
    <div class="FilesDiv">
        <h1>Files</h1>
        <div class="FilesDivSub">
            <form method="POST">
                <ul>
                    {% for i,j in files_info_lists %}
                    <li>
                        <div class="file_row">
                            <a href="{{ url_for('main.download_data_page', file_name= i ) }}">{{ i }}</a> <i>{{ j }}</i>
                            <button class="btn btn-danger button_size" name="file_to_delete" value="{{ i }}"><i class="fa fa-trash"></i> Trash</button>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </form>
        </div>
    </div>
</div>


</section>


<script>
    function update() {
        var element = document.getElementById("myprogressBar");   
        var width = 10;
        var identity = setInterval(scene, 10);
        function scene() {
        if (width >= 100) {
            clearInterval(identity);
        } else {
            width++; 
            element.style.width = width + '%'; 
            }
        }
    }
    </script>

{% endblock %}

app_package/templates/upload_page_mock.html
{% extends "layout.html" %}
{% block title %} File Share {% endblock %}
{% block main %}


<section class="FileManager">
  <div class="PageDiv">
    
    <div class="SeachLocalDiv">
      <h1>Upload</h1>

      {% if selected_files %}
        <form method="POST">
          
          <div class="FilesStagedForUpload">
            Upload these files:
            {% for file in selected_files %}
              {% if file == selected_files[-1] %}
              <u class="fileNameColor">{{ file }}</u>
              {% else %}
              <u class="fileNameColor">{{ file }}</u>,
              {% endif %}
            {% endfor %}
          
            <div class="UploadStaging">

              <div class="ButtonDiv2">
                <button type="button" data-bs-toggle="modal" data-bs-target="#explorerModal" class="btn btn-secondary "> Browse</button>
                <button type="submit" name="upload" value="True" class="btn btn-info "> Upload</button>
              </div>
            </div>
          </div>
          
        </form>

        {% else %}

        <div class="ButtonDiv">
          <button type="button" data-bs-toggle="modal" data-bs-target="#explorerModal" data-bs-whatever="something passed to java" >
            <img src="../static/images/FileExplorerButton.PNG">
          </button>
          <div>* This is a mock local drive to test what it would be like to upload a file.</div>
        </div>

      {% endif %}
    </div>

    {% if len(upload_file_dict)>0 %}
    <hr/>
    <div class="FilesDiv">
      <h1>Files</h1>
      <div class="FilesDivSub">
          <form method="POST">
              <ul>
                  {% for i,j in upload_file_dict.items() %}
                  <li>
                      <div class="file_row">
                          <a href="{{ url_for('main.download_data_page', file_name= i ) }}">{{ i }}</a> <i>{{ j }}</i>
                          <button class="btn btn-danger button_size" name="file_to_delete" value="{{ i }}"><i class="fa fa-trash"></i> Trash</button>
                      </div>
                  </li>
                  {% endfor %}
              </ul>
          </form>
      </div>
    </div>
    {% endif %}
  </div>
</section>






<form method="POST" action="" enctype="multipart/form-data">
    
    
  <!-- Modal -->
  <div class="modal" id="explorerModal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header header_custom">
            <!-- Nav bar for folder look -->
          <div class="breadcrumbs_path">.../Your Local Directory</div>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          </button>
        </div>
        <!-- files section -->
        <div class="modal-body">
            <div class="folder_look">
                
                {% for i, j in local_files_info_dict.items() %}
                  <div class="file_item">
                    {% if j[1]==True %}
                      <input type="checkbox" class="custom-control-input" name="file_{{ i }}" checked/>
                      {% else %}
                      <input type="checkbox" class="custom-control-input" name="file_{{ i }}" />
                    {% endif %}
                    <span class="file_text">{{ i }}</span>
                  </div>
                {% endfor %}
        </div>
        <div class="modal-footer custom_footer">
          <button type="submit" class="btn btn-primary" name="select_file" value="True">Select</button>
        </div>
      </div>
    </div>
  </div>
</form>


<!-- 
<script>

function _(el) {
  return document.getElementById(el);
}

function uploadFile() {
  var file = _("file2").files[0];
  // alert(file.name+" | "+file.size+" | "+file.type);
  var formdata = new FormData();
  formdata.append("file2", file);
  var ajax = new XMLHttpRequest();
  ajax.upload.addEventListener("progress", progressHandler, false);
  ajax.addEventListener("load", completeHandler, false);
  ajax.addEventListener("error", errorHandler, false);
  ajax.addEventListener("abort", abortHandler, false);
  ajax.open("POST", "file_upload_parser.php"); // http://www.developphp.com/video/JavaScript/File-Upload-Progress-Bar-Meter-Tutorial-Ajax-PHP
  //use file_upload_parser.php from above url
  ajax.send(formdata);
}

function progressHandler(event) {
  _("loaded_n_total").innerHTML = "Uploaded " + event.loaded + " bytes of " + event.total;
  var percent = (event.loaded / event.total) * 100;
  _("progressBar").value = Math.round(percent);
  _("status").innerHTML = Math.round(percent) + "% uploaded... please wait";
}

function completeHandler(event) {
  _("status").innerHTML = event.target.responseText;
  _("progressBar").value = 0; //wil clear progress bar after successful upload
}

function errorHandler(event) {
  _("status").innerHTML = "Upload Failed";
}

function abortHandler(event) {
  _("status").innerHTML = "Upload Aborted";
}

</script> -->


{% endblock %}